/* parser generated by jison 0.4.17 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var Parser = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,6],$V1=[1,8],$V2=[1,9],$V3=[1,10],$V4=[1,11],$V5=[1,12],$V6=[1,13],$V7=[8,21,22,23,24,25,26],$V8=[6,21,22,23,24,25,26],$V9=[1,25],$Va=[1,26],$Vb=[11,15],$Vc=[6,21,22,23,24,25,26,29],$Vd=[1,52],$Ve=[15,33],$Vf=[6,21,22,23,24,25,26,29,31,34],$Vg=[1,63],$Vh=[1,64],$Vi=[1,66],$Vj=[1,67],$Vk=[1,65],$Vl=[15,33,40,44,53],$Vm=[15,40],$Vn=[44,53];
var parser = {trace: function trace() { },
yy: {},
symbols_: {"error":2,"file":3,"imports":4,"routes":5,"EOF":6,"import":7,"%":8,"IMPORT":9,"member_list":10,"FROM":11,"string_literal":12,"AS":13,"identifier":14,",":15,"route":16,"method":17,"pattern":18,"=":19,"filters":20,"GET":21,"PATCH":22,"POST":23,"PUT":24,"DELETE":25,"HEAD":26,"PATH":27,"filter":28,"|":29,"member_identifier":30,"(":31,"arguments":32,")":33,".":34,"kvp":35,"value":36,"value_group0":37,"list":38,"[":39,"]":40,"value_list":41,"dict":42,"{":43,"}":44,"dict_repetition_plus0":45,"kvps":46,"STRING_LITERAL":47,"boolean_literal":48,"TRUE":49,"FALSE":50,"number_literal":51,"NUMBER_LITERAL":52,"IDENTIFIER":53,"$accept":0,"$end":1},
terminals_: {2:"error",6:"EOF",8:"%",9:"IMPORT",11:"FROM",13:"AS",15:",",19:"=",21:"GET",22:"PATCH",23:"POST",24:"PUT",25:"DELETE",26:"HEAD",27:"PATH",29:"|",31:"(",33:")",34:".",39:"[",40:"]",43:"{",44:"}",47:"STRING_LITERAL",49:"TRUE",50:"FALSE",52:"NUMBER_LITERAL",53:"IDENTIFIER"},
productions_: [0,[3,3],[3,2],[4,1],[4,2],[7,5],[7,5],[10,1],[10,3],[5,1],[5,2],[16,4],[17,1],[17,1],[17,1],[17,1],[17,1],[17,1],[18,1],[20,1],[20,3],[28,1],[28,1],[28,4],[28,4],[28,1],[30,3],[30,3],[32,1],[32,3],[36,1],[38,2],[38,3],[41,1],[41,3],[42,2],[42,3],[46,1],[46,2],[35,3],[12,1],[48,1],[48,1],[51,1],[14,1],[37,1],[37,1],[37,1],[37,1],[37,1],[45,1],[45,2]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:
this.$ = new yy.ast.File($$[$0-2], $$[$0-1], this._$); return this.$;
break;
case 2:
this.$ = new yy.ast.File([], $$[$0-1], this._$); return this.$;
break;
case 3:
this.$ = [$$[$0]];           
break;
case 4:
this.$ = $$[$0-1].concat($$[$0]);  
break;
case 5:
this.$ = new yy.ast.MemberImport($$[$0-2], $$[$0], this._$);        
break;
case 6:
this.$ = new yy.ast.QualifiedImport($$[$0-2], $$[$0], this._$); 
break;
case 7:
this.$ =[$$[$0]];           
break;
case 8: case 20:
this.$ = $$[$0-2].concat($$[$0]); 
break;
case 9: case 28: case 33: case 37:
this.$ = [$$[$0]];         
break;
case 10: case 38:
this.$ = $$[$0-1].concat($$[$0]);
break;
case 11:
this.$ = new yy.ast.Route($$[$0-3], $$[$0-2], $$[$0], this._$);    
break;
case 17:
this.$ = $$[$0];
break;
case 18:
this.$ = new yy.ast.Pattern($$[$0], this._$);
break;
case 19:
this.$ = [$$[$0]];  
break;
case 21: case 22:
this.$ = new yy.ast.CurriedFilter($$[$0], [], this._$); 
break;
case 23: case 24:
this.$ = new yy.ast.CurriedFilter($$[$0-3], $$[$0-1], this._$); 
break;
case 25:
this.$ = new yy.ast.RenderFilter($$[$0], this._$); 
break;
case 26: case 27:
this.$ = new yy.ast.MemberIdentifier($$[$0-2], $$[$0], this._$);
break;
case 29: case 34:
this.$ = $$[$0-2].concat($$[$0]);
break;
case 31:
this.$ = new yy.ast.List([], this._$); 
break;
case 32:
this.$ = new yy.ast.List($$[$0-1], this._$); 
break;
case 35:
this.$ = new yy.ast.Dict([], this._$); 
break;
case 36:
this.$ = new yy.ast.Dict($$[$0-1], this._$); 
break;
case 39:
this.$ = new yy.ast.KVP($$[$0-2], $$[$0], this._$);
break;
case 40:
this.$ = new yy.ast.StringLiteral($$[$0].slice(1, -1), this._$); 
break;
case 41:
this.$ = new yy.ast.BooleanLiteral(true, this._$);
break;
case 42:
this.$ = new yy.ast.BooleanLiteral(false, this._$);
break;
case 43:
this.$ = new yy.ast.NumberLiteral(parseFloat($$[$0]), this._$); 
break;
case 44:
this.$ = new yy.ast.Identifier($$[$0], this._$);
break;
case 50:
this.$ = [$$[$0]];
break;
case 51:
$$[$0-1].push($$[$0]);
break;
}
},
table: [{3:1,4:2,5:3,7:4,8:$V0,16:5,17:7,21:$V1,22:$V2,23:$V3,24:$V4,25:$V5,26:$V6},{1:[3]},{5:14,7:15,8:$V0,16:5,17:7,21:$V1,22:$V2,23:$V3,24:$V4,25:$V5,26:$V6},{6:[1,16],16:17,17:7,21:$V1,22:$V2,23:$V3,24:$V4,25:$V5,26:$V6},o($V7,[2,3]),o($V8,[2,9]),{9:[1,18]},{18:19,27:[1,20]},{27:[2,12]},{27:[2,13]},{27:[2,14]},{27:[2,15]},{27:[2,16]},{27:[2,17]},{6:[1,21],16:17,17:7,21:$V1,22:$V2,23:$V3,24:$V4,25:$V5,26:$V6},o($V7,[2,4]),{1:[2,2]},o($V8,[2,10]),{10:22,12:23,14:24,47:$V9,53:$Va},{19:[1,27]},{19:[2,18]},{1:[2,1]},{11:[1,28],15:[1,29]},{13:[1,30]},o($Vb,[2,7]),o([6,8,13,15,21,22,23,24,25,26,29,33,40,44,53],[2,40]),o([6,8,11,15,19,21,22,23,24,25,26,29,31,34],[2,44]),{12:35,14:33,20:31,28:32,30:34,47:$V9,53:$Va},{12:36,47:$V9},{14:37,53:$Va},{14:38,53:$Va},o($V8,[2,11],{29:[1,39]}),o($Vc,[2,19]),o($Vc,[2,21],{31:[1,40],34:[1,41]}),o($Vc,[2,22],{31:[1,42],34:[1,43]}),o($Vc,[2,25]),o($V7,[2,5]),o($Vb,[2,8]),o($V7,[2,6]),{12:35,14:33,28:44,30:34,47:$V9,53:$Va},{14:47,32:45,35:46,53:$Va},{14:48,53:$Va},{14:47,32:49,35:46,53:$Va},{14:50,53:$Va},o($Vc,[2,20]),{15:$Vd,33:[1,51]},o($Ve,[2,28]),{19:[1,53]},o($Vf,[2,26]),{15:$Vd,33:[1,54]},o($Vf,[2,27]),o($Vc,[2,23]),{14:47,35:55,53:$Va},{12:60,36:56,37:57,38:58,39:$Vg,42:59,43:$Vh,47:$V9,48:62,49:$Vi,50:$Vj,51:61,52:$Vk},o($Vc,[2,24]),o($Ve,[2,29]),o([15,33,44,53],[2,39]),o($Vl,[2,30]),o($Vl,[2,45]),o($Vl,[2,46]),o($Vl,[2,47]),o($Vl,[2,48]),o($Vl,[2,49]),{12:60,36:70,37:57,38:58,39:$Vg,40:[1,68],41:69,42:59,43:$Vh,47:$V9,48:62,49:$Vi,50:$Vj,51:61,52:$Vk},{14:47,35:73,44:[1,71],45:72,53:$Va},o($Vl,[2,43]),o($Vl,[2,41]),o($Vl,[2,42]),o($Vl,[2,31]),{15:[1,75],40:[1,74]},o($Vm,[2,33]),o($Vl,[2,35]),{14:47,35:77,44:[1,76],53:$Va},o($Vn,[2,50]),o($Vl,[2,32]),{12:60,36:78,37:57,38:58,39:$Vg,42:59,43:$Vh,47:$V9,48:62,49:$Vi,50:$Vj,51:61,52:$Vk},o($Vl,[2,36]),o($Vn,[2,51]),o($Vm,[2,34])],
defaultActions: {8:[2,12],9:[2,13],10:[2,14],11:[2,15],12:[2,16],13:[2,17],16:[2,2],20:[2,18],21:[2,1]},
parseError: function parseError(str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        function _parseError (msg, hash) {
            this.message = msg;
            this.hash = hash;
        }
        _parseError.prototype = Error;

        throw new _parseError(str, hash);
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};

/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function (match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex() {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin(condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState() {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules() {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState(n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState(condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {"flex":true},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:return;
break;
case 1:return;
break;
case 2:return 49;
break;
case 3:return 50;
break;
case 4:return 21;
break;
case 5:return 22;
break;
case 6:return 23;
break;
case 7:return 24;
break;
case 8:return 25;
break;
case 9:return 26;
break;
case 10:return 9;
break;
case 11:return 13;
break;
case 12:return 11;
break;
case 13:return 31;
break;
case 14:return 33;
break;
case 15:return 39;
break;
case 16:return 40;
break;
case 17:return 8;
break;
case 18:return 29;
break;
case 19:return ';';
break;
case 20:return ':';
break;
case 21:return 19;
break;
case 22:return 15;
break;
case 23:return 34;
break;
case 24:return 43;
break;
case 25:return 44;
break;
case 26:return 27;
break;
case 27:return '/';
break;
case 28:return 52;
break;
case 29:return 47;
break;
case 30:return 53;
break;
case 31:return 6;
break;
case 32:console.log(yy_.yytext);
break;
}
},
rules: [/^(?:\s+)/,/^(?:#.*)/,/^(?:true)/,/^(?:false)/,/^(?:GET)/,/^(?:PATCH)/,/^(?:POST)/,/^(?:PUT)/,/^(?:DELETE)/,/^(?:HEAD)/,/^(?:import)/,/^(?:as)/,/^(?:from)/,/^(?:\()/,/^(?:\))/,/^(?:\[)/,/^(?:\])/,/^(?:%)/,/^(?:\|)/,/^(?:;)/,/^(?::)/,/^(?:=)/,/^(?:,)/,/^(?:\.)/,/^(?:\{)/,/^(?:\})/,/^(?:((\/[\w:]+)+|[\/]))/,/^(?:\/)/,/^(?:((([-]?([-]?([0]|(([1-9])([0-9]+)*)))\.([0-9]+)*(([eE])([+-]?[0-9]+))?)|(\.([0-9]+)(([eE])([+-]?[0-9]+))?)|(([-]?([0]|(([1-9])([0-9]+)*)))(([eE])([+-]?[0-9]+))?))|([0][xX]([0-9a-fA-F])+)|([0]([0-7])+)))/,/^(?:(("(([^\"\\\n\r]+)|(\\((([\'\"\\bfnrtv])|([^\'\"\\bfnrtv0-9xu]))|((?:[1-7][0-7]{0,2}|[0-7]{2,3}))|([x]([0-9a-fA-F]){2})|([u]([0-9a-fA-F]){4})))|(\\(\r\n|\r|\n)))*")|('(([^\'\\\n\r]+)|(\\((([\'\"\\bfnrtv])|([^\'\"\\bfnrtv0-9xu]))|((?:[1-7][0-7]{0,2}|[0-7]{2,3}))|([x]([0-9a-fA-F]){2})|([u]([0-9a-fA-F]){4})))|(\\(\r\n|\r|\n)))*')|(`(([^\`\\\n\r]+)|(\\((([\'\"\\bfnrtv])|([^\'\"\\bfnrtv0-9xu]))|((?:[1-7][0-7]{0,2}|[0-7]{2,3}))|([x]([0-9a-fA-F]){2})|([u]([0-9a-fA-F]){4})))|(\\(\r\n|\r|\n)))*`)))/,/^(?:([a-zA-Z$_][a-zA-Z$_0-9-]*))/,/^(?:$)/,/^(?:.)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = Parser;
exports.Parser = Parser.Parser;
exports.parse = function () { return Parser.parse.apply(Parser, arguments); };
exports.main = function commonjsMain(args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}